apiVersion: v1
name: jupyterhub
version: 0.9.0
appVersion: 1.1.0
description: Nublado2 JupyterHub installation
home: https://github.com/lsst-sqre/nublado2
maintainers:
  - name: cbanek
sources:
  - https://github.com/lsst-sqre/nublado2
  - https://github.com/lsst-sqre/charts
kubeVersion: '>=1.11.0-0'
